/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Generates a WebP thumbnail for a supported file path or in-memory bytes.
 *
 * Supports image, document, presentation, spreadsheet, and text inputs.
 *
 * @param input - Absolute or relative path to the source file, or source bytes as a Node.js `Buffer`.
 * @param width - Target thumbnail width in pixels.
 * @param height - Target thumbnail height in pixels.
 * @param mime_type - Optional MIME type when `input` is a `Buffer` (for example `image/jpeg` or `text/plain`).
 * @returns A WebP-encoded thumbnail as a Node.js `Buffer`.
 *
 * @example
 * ```ts
 * import { writeFileSync } from 'node:fs';
 * import { generateThumbnail } from 'sipat';
 *
 * const output = generateThumbnail('./tests/documents/test-image.jpeg', 320, 240);
 * writeFileSync('./thumbnail.webp', output);
 *
 * const source = Buffer.from('hello from memory');
 * const fromBuffer = generateThumbnail(source, 320, 240, 'text/plain');
 * writeFileSync('./thumbnail-from-buffer.webp', fromBuffer);
 * ```
 */
export declare function generateThumbnail(input: string | Buffer, width: number, height: number, mimeType?: string | undefined | null): Buffer
